package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/BangRocket/MyPal/apps/backend/internal/application/graphql/generated"
)

// EmailConfig is the resolver for the emailConfig field.
func (r *queryResolver) EmailConfig(ctx context.Context) (*generated.EmailChannelConfig, error) {
	ec := r.Deps.EmailConfig

	// Convert config filter rules to GraphQL model.
	filters := make([]*generated.EmailFilterRule, 0, len(ec.Filters))
	for _, f := range ec.Filters {
		filters = append(filters, &generated.EmailFilterRule{
			Field:   f.Field,
			Pattern: f.Pattern,
			Action:  f.Action,
		})
	}

	return &generated.EmailChannelConfig{
		Enabled:        ec.Enabled,
		ImapHost:       ec.IMAPHost,
		ImapPort:       ec.IMAPPort,
		ImapUser:       ec.IMAPUser,
		ImapTLS:        ec.IMAPTLS,
		SMTPHost:       ec.SMTPHost,
		SMTPPort:       ec.SMTPPort,
		SMTPFrom:       ec.SMTPFrom,
		SMTPTLS:        ec.SMTPTLS,
		PollInterval:   ec.PollInterval,
		ProcessedLabel: ec.ProcessedLabel,
		Filters:        filters,
	}, nil
}
