package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/BangRocket/MyPal/apps/backend/internal/application/graphql/generated"
)

// CreateHeartbeatItem is the resolver for the createHeartbeatItem field.
func (r *mutationResolver) CreateHeartbeatItem(ctx context.Context, input generated.HeartbeatItemInput) (*generated.HeartbeatItem, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.CreateHeartbeatItem(ctx, input)
}

// UpdateHeartbeatItem is the resolver for the updateHeartbeatItem field.
func (r *mutationResolver) UpdateHeartbeatItem(ctx context.Context, id string, input generated.HeartbeatItemInput) (*generated.HeartbeatItem, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.UpdateHeartbeatItem(ctx, id, input)
}

// DeleteHeartbeatItem is the resolver for the deleteHeartbeatItem field.
func (r *mutationResolver) DeleteHeartbeatItem(ctx context.Context, id string) (bool, error) {
	if r.Deps == nil {
		return false, nil
	}
	return r.Deps.DeleteHeartbeatItem(ctx, id)
}

// SnoozeHeartbeatItem is the resolver for the snoozeHeartbeatItem field.
func (r *mutationResolver) SnoozeHeartbeatItem(ctx context.Context, id string, until string) (*generated.HeartbeatItem, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.SnoozeHeartbeatItem(ctx, id, until)
}

// CompleteHeartbeatItem is the resolver for the completeHeartbeatItem field.
func (r *mutationResolver) CompleteHeartbeatItem(ctx context.Context, id string) (bool, error) {
	if r.Deps == nil {
		return false, nil
	}
	return r.Deps.CompleteHeartbeatItem(ctx, id)
}

// HeartbeatItems is the resolver for the heartbeatItems field.
func (r *queryResolver) HeartbeatItems(ctx context.Context) ([]*generated.HeartbeatItem, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.HeartbeatItems(ctx)
}

// HeartbeatItem is the resolver for the heartbeatItem field.
func (r *queryResolver) HeartbeatItem(ctx context.Context, id string) (*generated.HeartbeatItem, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.HeartbeatItemByID(ctx, id)
}

// HeartbeatLogs is the resolver for the heartbeatLogs field.
func (r *queryResolver) HeartbeatLogs(ctx context.Context, itemID string, limit *int) ([]*generated.HeartbeatLog, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.HeartbeatLogs(ctx, itemID, limit)
}

// ExportHeartbeat is the resolver for the exportHeartbeat field.
func (r *queryResolver) ExportHeartbeat(ctx context.Context) (string, error) {
	if r.Deps == nil {
		return "", nil
	}
	return r.Deps.ExportHeartbeat(ctx)
}
