package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/BangRocket/MyPal/apps/backend/internal/application/graphql/generated"
	"github.com/BangRocket/MyPal/apps/backend/internal/application/graphql/resolvers/mappers"
	"github.com/BangRocket/MyPal/apps/backend/internal/application/graphql/resolvers/utils"
	memorysvc "github.com/BangRocket/MyPal/apps/backend/internal/domain/services/memory"
	"github.com/google/uuid"
)

// AddMemory is the resolver for the addMemory field.
func (r *mutationResolver) AddMemory(ctx context.Context, content string) (*generated.MutationResult, error) {
	if r.Deps == nil {
		return &generated.MutationResult{Success: true}, nil
	}
	err := r.Deps.AddMemory(ctx, "dashboard", content)
	result := &generated.MutationResult{Success: err == nil}
	if err != nil {
		errStr := err.Error()
		result.Error = &errStr
	}
	return result, nil
}

// AddMemoryNode is the resolver for the addMemoryNode field.
func (r *mutationResolver) AddMemoryNode(ctx context.Context, label string, typeArg string, value string) (*generated.MemoryNode, error) {
	if r.Deps == nil {
		return nil, nil
	}
	id, err := r.Deps.AddMemoryNode(ctx, label, typeArg, value)
	if err != nil {
		return nil, err
	}
	if id == "" {
		id = uuid.New().String()
	}
	return &generated.MemoryNode{
		ID:    id,
		Label: &label,
		Type:  &typeArg,
		Value: &value,
	}, nil
}

// UpdateMemoryNode is the resolver for the updateMemoryNode field.
func (r *mutationResolver) UpdateMemoryNode(ctx context.Context, id string, label *string, typeArg *string, value *string, properties *string) (*generated.MemoryNode, error) {
	if r.Deps == nil {
		return nil, nil
	}
	lbl, typ, val := utils.PtrStr(label), utils.PtrStr(typeArg), utils.PtrStr(value)
	props := utils.ParseProperties(properties)
	if err := r.Deps.UpdateMemoryNode(ctx, id, lbl, typ, val, props); err != nil {
		return nil, err
	}
	return &generated.MemoryNode{
		ID:         id,
		Label:      label,
		Type:       typeArg,
		Value:      value,
		Properties: utils.PropsToAny(props),
	}, nil
}

// DeleteMemoryNode is the resolver for the deleteMemoryNode field.
func (r *mutationResolver) DeleteMemoryNode(ctx context.Context, id string) (bool, error) {
	if r.Deps == nil {
		return true, nil
	}
	err := r.Deps.DeleteMemoryNode(ctx, id)
	return err == nil, err
}

// AddRelation is the resolver for the addRelation field.
func (r *mutationResolver) AddRelation(ctx context.Context, from string, to string, relationType string) (*generated.AddRelationResult, error) {
	if r.Deps == nil {
		return &generated.AddRelationResult{Success: true}, nil
	}
	err := r.Deps.AddRelation(ctx, from, to, relationType)
	result := &generated.AddRelationResult{Success: err == nil}
	if err != nil {
		errStr := err.Error()
		result.Error = &errStr
	}
	return result, nil
}

// ExecuteCypher is the resolver for the executeCypher field.
func (r *mutationResolver) ExecuteCypher(ctx context.Context, cypher string) (*generated.CypherResult, error) {
	if r.Deps == nil {
		return &generated.CypherResult{Success: true}, nil
	}
	_, err := r.Deps.ExecuteCypher(ctx, cypher)
	result := &generated.CypherResult{Success: err == nil}
	if err != nil {
		errStr := err.Error()
		result.Error = &errStr
	}
	return result, nil
}

// RememberMemory is the resolver for the rememberMemory field.
func (r *mutationResolver) RememberMemory(ctx context.Context, userID string, content string, metadata *string) (bool, error) {
	if r.Deps == nil || r.Deps.MemorySys == nil {
		return false, fmt.Errorf("memory system not available")
	}
	var meta map[string]any
	if metadata != nil && *metadata != "" {
		if err := json.Unmarshal([]byte(*metadata), &meta); err != nil {
			return false, fmt.Errorf("invalid metadata JSON: %w", err)
		}
	}
	if err := r.Deps.MemorySys.Remember(ctx, userID, content, meta); err != nil {
		return false, err
	}
	return true, nil
}

// ForgetMemory is the resolver for the forgetMemory field.
func (r *mutationResolver) ForgetMemory(ctx context.Context, id string) (bool, error) {
	if r.Deps == nil || r.Deps.MemorySys == nil {
		return false, fmt.Errorf("memory system not available")
	}
	if err := r.Deps.MemorySys.Vector.Forget(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// BootstrapMemory is the resolver for the bootstrapMemory field.
func (r *mutationResolver) BootstrapMemory(ctx context.Context, userID string, profile string) (bool, error) {
	if r.Deps == nil || r.Deps.MemorySys == nil {
		return false, fmt.Errorf("memory system not available")
	}
	var p memorysvc.UserProfile
	if err := json.Unmarshal([]byte(profile), &p); err != nil {
		return false, fmt.Errorf("invalid profile JSON: %w", err)
	}
	if err := r.Deps.MemorySys.Bootstrap(ctx, userID, p); err != nil {
		return false, err
	}
	return true, nil
}

// SearchMemory is the resolver for the searchMemory field.
func (r *queryResolver) SearchMemory(ctx context.Context, query string) (*generated.SearchMemoryResult, error) {
	if r.Deps == nil {
		return &generated.SearchMemoryResult{Success: true, Result: utils.StringPtr("")}, nil
	}
	result, err := r.Deps.SearchMemory(ctx, "", query)
	res := &generated.SearchMemoryResult{Success: err == nil, Result: &result}
	if err != nil {
		errStr := err.Error()
		res.Error = &errStr
	}
	return res, nil
}

// UserGraph is the resolver for the userGraph field.
func (r *queryResolver) UserGraph(ctx context.Context, userID *string) (*generated.UserGraphResult, error) {
	if r.Deps == nil {
		return &generated.UserGraphResult{Success: true, Nodes: []*generated.GraphNode{}, Edges: []*generated.GraphEdge{}}, nil
	}
	uid := ""
	if userID != nil {
		uid = *userID
	}
	snap, err := r.Deps.UserGraph(ctx, uid)
	if err != nil {
		errStr := err.Error()
		return &generated.UserGraphResult{Success: false, Error: &errStr}, nil
	}
	if snap == nil {
		return &generated.UserGraphResult{Success: true, Nodes: []*generated.GraphNode{}, Edges: []*generated.GraphEdge{}}, nil
	}
	return &generated.UserGraphResult{
		Success: true,
		Nodes:   mappers.GraphNodesToGenerated(snap.Nodes),
		Edges:   mappers.GraphEdgesToGenerated(snap.Edges),
	}, nil
}

// Memory is the resolver for the memory field.
func (r *queryResolver) Memory(ctx context.Context) (*generated.MemoryGraph, error) {
	if r.Deps == nil {
		return &generated.MemoryGraph{Nodes: []*generated.MemoryNode{}, Edges: []*generated.MemoryEdge{}}, nil
	}
	snap, err := r.Deps.MemoryGraph(ctx)
	if err != nil {
		return nil, err
	}
	if snap == nil {
		return &generated.MemoryGraph{Nodes: []*generated.MemoryNode{}, Edges: []*generated.MemoryEdge{}}, nil
	}
	return &generated.MemoryGraph{
		Nodes: mappers.MemoryNodesFromSnapshot(snap.Nodes),
		Edges: mappers.MemoryEdgesFromSnapshot(snap.Edges),
	}, nil
}

// VectorSearch is the resolver for the vectorSearch field.
func (r *queryResolver) VectorSearch(ctx context.Context, userID string, query string, topK *int) ([]*generated.VectorSearchResult, error) {
	if r.Deps == nil || r.Deps.MemorySys == nil {
		return []*generated.VectorSearchResult{}, nil
	}
	k := 10
	if topK != nil && *topK > 0 {
		k = *topK
	}
	results, err := r.Deps.MemorySys.Recall(ctx, userID, query, k)
	if err != nil {
		return nil, err
	}
	var out []*generated.VectorSearchResult
	for _, m := range results {
		var metaStr *string
		if m.Metadata != nil {
			b, _ := json.Marshal(m.Metadata)
			s := string(b)
			metaStr = &s
		}
		createdAt := time.Now().UTC().Format(time.RFC3339)
		if t, ok := m.Metadata["created_at"].(string); ok && t != "" {
			createdAt = t
		}
		out = append(out, &generated.VectorSearchResult{
			ID:        m.ID,
			Content:   m.Content,
			Score:     m.Score,
			UserID:    userID,
			Metadata:  metaStr,
			CreatedAt: createdAt,
		})
	}
	return out, nil
}

// GraphNeighbors is the resolver for the graphNeighbors field.
func (r *queryResolver) GraphNeighbors(ctx context.Context, entityID string, depth *int) (*generated.GraphNeighborResult, error) {
	if r.Deps == nil || r.Deps.MemorySys == nil || r.Deps.MemorySys.Graph == nil {
		return &generated.GraphNeighborResult{
			Entities:  []*generated.GraphEntity{},
			Relations: []*generated.GraphRelation{},
		}, nil
	}
	d := 1
	if depth != nil && *depth > 0 {
		d = *depth
	}
	entities, relations, err := r.Deps.MemorySys.Graph.GetNeighbors(ctx, entityID, d)
	if err != nil {
		return nil, err
	}
	var gqlEntities []*generated.GraphEntity
	for _, e := range entities {
		var propsStr *string
		if e.Properties != nil {
			b, _ := json.Marshal(e.Properties)
			s := string(b)
			propsStr = &s
		}
		gqlEntities = append(gqlEntities, &generated.GraphEntity{
			ID:         e.ID,
			Type:       e.Type,
			Name:       e.Name,
			UserID:     e.UserID,
			Properties: propsStr,
			CreatedAt:  e.CreatedAt.Format(time.RFC3339),
		})
	}
	var gqlRelations []*generated.GraphRelation
	for _, rel := range relations {
		var metaStr *string
		if rel.Metadata != nil {
			b, _ := json.Marshal(rel.Metadata)
			s := string(b)
			metaStr = &s
		}
		gqlRelations = append(gqlRelations, &generated.GraphRelation{
			ID:       rel.ID,
			FromID:   rel.FromID,
			ToID:     rel.ToID,
			Type:     rel.Type,
			Weight:   rel.Weight,
			Metadata: metaStr,
		})
	}
	if gqlEntities == nil {
		gqlEntities = []*generated.GraphEntity{}
	}
	if gqlRelations == nil {
		gqlRelations = []*generated.GraphRelation{}
	}
	return &generated.GraphNeighborResult{
		Entities:  gqlEntities,
		Relations: gqlRelations,
	}, nil
}

// MemoryStats is the resolver for the memoryStats field.
func (r *queryResolver) MemoryStats(ctx context.Context, userID string) (*generated.MemoryStats, error) {
	if r.Deps == nil || r.Deps.MemorySys == nil {
		return &generated.MemoryStats{}, nil
	}
	// Vector count: search with a broad query, count results.
	// For a proper count we'd need a Count method on VectorStore; for now
	// we approximate by searching with a high topK using a generic query.
	vectorCount := 0
	results, err := r.Deps.MemorySys.Recall(ctx, userID, "", 1000)
	if err == nil {
		vectorCount = len(results)
	}

	entityCount := 0
	relationCount := 0
	if r.Deps.MemorySys.Graph != nil {
		entities, relations, err := r.Deps.MemorySys.Graph.UserGraph(ctx, userID)
		if err == nil {
			entityCount = len(entities)
			relationCount = len(relations)
		}
	}
	return &generated.MemoryStats{
		VectorCount:   vectorCount,
		EntityCount:   entityCount,
		RelationCount: relationCount,
	}, nil
}
