package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/BangRocket/MyPal/apps/backend/internal/application/graphql/generated"
)

// ModelTiers is the resolver for the modelTiers field.
func (r *queryResolver) ModelTiers(ctx context.Context) (*generated.ModelTiersConfig, error) {
	mt := r.Deps.ModelTiers
	tiers := make([]*generated.ModelTier, len(mt.Tiers))
	for i, t := range mt.Tiers {
		tier := &generated.ModelTier{
			Name:      t.Name,
			Provider:  t.Provider,
			Model:     t.Model,
			Prefix:    t.Prefix,
			IsDefault: t.Default,
		}
		if t.CostCap > 0 {
			cap := t.CostCap
			tier.CostCap = &cap
		}
		tiers[i] = tier
	}
	return &generated.ModelTiersConfig{
		Enabled: mt.Enabled,
		Tiers:   tiers,
	}, nil
}
