package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/BangRocket/MyPal/apps/backend/internal/application/graphql/generated"
)

// UpdateOrganicConfig is the resolver for the updateOrganicConfig field.
func (r *mutationResolver) UpdateOrganicConfig(ctx context.Context, channelID string, input generated.OrganicResponseConfigInput) (*generated.OrganicResponseConfig, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.UpdateOrganicConfig(ctx, channelID, input)
}

// OrganicConfig is the resolver for the organicConfig field.
func (r *queryResolver) OrganicConfig(ctx context.Context, channelID string) (*generated.OrganicResponseConfig, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.OrganicConfig(ctx, channelID)
}
