package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/BangRocket/MyPal/apps/backend/internal/application/graphql/generated"
)

// CreatePersonality is the resolver for the createPersonality field.
func (r *mutationResolver) CreatePersonality(ctx context.Context, input generated.PersonalityInput) (*generated.Personality, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.CreatePersonality(ctx, input)
}

// UpdatePersonality is the resolver for the updatePersonality field.
func (r *mutationResolver) UpdatePersonality(ctx context.Context, id string, input generated.PersonalityInput) (*generated.Personality, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.UpdatePersonality(ctx, id, input)
}

// DeletePersonality is the resolver for the deletePersonality field.
func (r *mutationResolver) DeletePersonality(ctx context.Context, id string) (bool, error) {
	if r.Deps == nil {
		return false, nil
	}
	return r.Deps.DeletePersonality(ctx, id)
}

// SetDefaultPersonality is the resolver for the setDefaultPersonality field.
func (r *mutationResolver) SetDefaultPersonality(ctx context.Context, id string) (bool, error) {
	if r.Deps == nil {
		return false, nil
	}
	return r.Deps.SetDefaultPersonality(ctx, id)
}

// PreviewPersonality is the resolver for the previewPersonality field.
func (r *mutationResolver) PreviewPersonality(ctx context.Context, personalityID string, userID string, channelType string, testMessage string) (string, error) {
	if r.Deps == nil {
		return "", nil
	}
	return r.Deps.PreviewPersonality(ctx, personalityID, userID, channelType, testMessage)
}

// Personalities is the resolver for the personalities field.
func (r *queryResolver) Personalities(ctx context.Context) ([]*generated.Personality, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.Personalities(ctx)
}

// Personality is the resolver for the personality field.
func (r *queryResolver) Personality(ctx context.Context, id string) (*generated.Personality, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.Personality(ctx, id)
}

// UserRelationships is the resolver for the userRelationships field.
func (r *queryResolver) UserRelationships(ctx context.Context, userID string) ([]*generated.UserRelationship, error) {
	if r.Deps == nil {
		return nil, nil
	}
	return r.Deps.UserRelationships(ctx, userID)
}
