package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/BangRocket/MyPal/apps/backend/internal/application/graphql/generated"
	"github.com/BangRocket/MyPal/apps/backend/internal/domain/ports"
)

// CreateSandbox is the resolver for the createSandbox field.
func (r *mutationResolver) CreateSandbox(ctx context.Context, image string, persistent *bool) (*generated.SandboxInstance, error) {
	if r.Deps == nil || r.Deps.SandboxMgr == nil {
		return nil, fmt.Errorf("sandbox not enabled")
	}
	persist := false
	if persistent != nil {
		persist = *persistent
	}
	inst, err := r.Deps.SandboxMgr.CreateSandbox(ctx, "dashboard", ports.SandboxConfig{
		Image:      image,
		Persistent: persist,
	})
	if err != nil {
		return nil, err
	}
	return sandboxInstanceToGenerated(inst), nil
}

// ExecuteSandbox is the resolver for the executeSandbox field.
func (r *mutationResolver) ExecuteSandbox(ctx context.Context, id string, command string) (*generated.SandboxResult, error) {
	if r.Deps == nil || r.Deps.SandboxMgr == nil {
		return nil, fmt.Errorf("sandbox not enabled")
	}
	result, err := r.Deps.SandboxMgr.Execute(ctx, id, ports.SandboxCommand{Cmd: command})
	if err != nil {
		return nil, err
	}
	ms := int(result.Duration.Milliseconds())
	return &generated.SandboxResult{
		ExitCode:   result.ExitCode,
		Stdout:     result.Stdout,
		Stderr:     result.Stderr,
		DurationMs: ms,
	}, nil
}

// DestroySandbox is the resolver for the destroySandbox field.
func (r *mutationResolver) DestroySandbox(ctx context.Context, id string) (bool, error) {
	if r.Deps == nil || r.Deps.SandboxMgr == nil {
		return false, fmt.Errorf("sandbox not enabled")
	}
	if err := r.Deps.SandboxMgr.DestroySandbox(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// SandboxInstances is the resolver for the sandboxInstances field.
func (r *queryResolver) SandboxInstances(ctx context.Context) ([]*generated.SandboxInstance, error) {
	if r.Deps == nil || r.Deps.SandboxMgr == nil {
		return nil, nil
	}
	list, err := r.Deps.SandboxMgr.ListSandboxes(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*generated.SandboxInstance, len(list))
	for i := range list {
		out[i] = sandboxInstanceToGenerated(&list[i])
	}
	return out, nil
}

// SandboxInstance is the resolver for the sandboxInstance field.
func (r *queryResolver) SandboxInstance(ctx context.Context, id string) (*generated.SandboxInstance, error) {
	if r.Deps == nil || r.Deps.SandboxMgr == nil {
		return nil, nil
	}
	inst, err := r.Deps.SandboxMgr.GetSandbox(ctx, id)
	if err != nil {
		return nil, err
	}
	if inst == nil {
		return nil, nil
	}
	return sandboxInstanceToGenerated(inst), nil
}
